### ISSUE TITLE
When i use your code to build success ,how can i use this framework

### ISSUE THREAD

**Issue by harofan** [manifest/sdl-ios-framework#3]
when i add the framework to project,xcode tell me 
![2016-10-18 2 41 00](https://cloud.githubusercontent.com/assets/20294470/19466935/f21a437e-9540-11e6-8635-97e9899689ae.png)
i add the -Objc to the other link flag,but xcode still tell me these error.what should i do?My english is poor,maybe some sentence you cant understand.

**Comment by manifest** [comment]
The SDL2.framework requires two more frameworks (GameController and CoreMotion) with the current version of iOS SDK (10.0). I've just updated [SDL Templates for Xcode](https://github.com/manifest/sdl-ios-templates). You just need to check  the latest version out and build the example application within it. Please, confirm that it works for you.

**Comment by harofan** [comment]
@manifest You mean to develop the gameI would like to develop a cross-platform player.Use FFmpeg and SDL.

**Comment by harofan** [comment]
How to open by Xcode?
![2016-10-18 7 49 38](https://cloud.githubusercontent.com/assets/20294470/19476511/363b4456-956c-11e6-9494-9dfe8d0cd925.png)

**Comment by harofan** [comment]
I know how to use your template just now.But it is not use appdelegate,how can i add sdl2 to normal APP?When i play the movie ,i want to use sdl.

**Comment by manifest** [comment]
You need to add all the frameworks of example application to your existing application. Or start a new one from the SDL template.

**Comment by harofan** [comment]
@manifest Thanks a lot.You solved my four-day problem.I also add all the frameworks to project,but search path is error.Finally, let me say a word to you in my native language.
"谢谢"

**Comment by manifest** [comment]
Nice to hear that you've solved the problem. And yes, you also needed to add a path where SDL2.framework is located to "Framework Search Paths" property to "Build Settings" (for the example application, its value is set to "~/Library/Frameworks").

**Comment by harofan** [comment]
Can I promote your template? Of course, i will be marked with the source

**Comment by manifest** [comment]
You can use it like you wish :-)
